import './globals.css';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'CarStock - Sistema de Estoque de Veículos',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="pt-BR">
      <body>{children}</body>
    </html>
  );
}
